const api = {
  VERSION: '0',
  actions: [
    'MPD_API_ADD_PLAYLIST',
    'MPD_API_ADD_PLAY_TRACK',
    'MPD_API_ADD_TRACK',
    'MPD_API_GET_BROWSE',
    'MPD_API_GET_MPDHOST',
    'MPD_API_GET_OUTPUTS',
    'MPD_API_GET_QUEUE',
    'MPD_API_PLAY_TRACK',
    'MPD_API_RM_TRACK',
    'MPD_API_SAVE_QUEUE',
    'MPD_API_SEARCH',
    'MPD_API_SET_MPDHOST',
    'MPD_API_SET_MPDPASS',
    'MPD_API_SET_NEXT',
    'MPD_API_SET_PAUSE',
    'MPD_API_SET_PLAY',
    'MPD_API_SET_PREV',
    'MPD_API_SET_SEEK',
    'MPD_API_SET_VOLUME',
    'MPD_API_TOGGLE_CONSUME',
    'MPD_API_TOGGLE_CROSSFADE',
    'MPD_API_TOGGLE_OUTPUT',
    'MPD_API_TOGGLE_RANDOM',
    'MPD_API_TOGGLE_REPEAT',
    'MPD_API_TOGGLE_SINGLE',
    'MPD_API_UPDATE_DB',
    'NL_DISCONNECT',
    'NL_JOIN',
    'NL_LIST',
    'NL_RESET',
    'NL_SCAN',
    'SYS_RESET',
    'SYS_RESTART',
    'SYS_UPGRADE',
  ],
  events: [
    'state',
    'browse',
    'outputnames',
    'outputs',
  ],
};

module.exports = api;
